config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :blogs

  match '/', to: 'blogs#index', constraints: { subdomain: 'www' }, via: [:get, :post, :put, :patch, :delete]
  match '/', to: 'blogs#show', constraints: { subdomain: /.+/ }, via: [:get, :post, :put, :patch, :delete]

  root to: "blogs#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :get_blog

private
  def get_blog

    blogs = Blog.where(subdomain: request.subdomain)

    if blogs.count > 0
      @blog = blogs.first
    elsif request.subdomain != 'www'
    	redirect_to root_url(subdomain: 'www')
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def show
    @posts = @blog.posts
  end



  def create
    @blog = Blog.create(blog_params)
  end
end
private

def blog_params
  params.require(:blog).permit(:name, :subdomain)
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def new
    @post = Post.new
  end

  def show
    @post = @blog.posts.find(params[:id])
  end

  def create
    @post = @blog.posts.create(post_params)
    respond_to do |format|
      format.html { render :controller => "blogs", :action => "show"}
      format.json { render json: @resource }
    end
  end

end
private

def post_params
  params.require(:post).permit(:title, :body, :blog_id)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/blogs/create.html.erb
<h1>You just made a new blog!</h1>

<%= link_to "Check Out Your New Blog!",  root_url(subdomain: @blog.subdomain) %>

app/views/blogs/index.html.erb
<h1>Blog Directory</h1><br />

<h1><%= link_to "Make A New Blog", new_blog_path %></h1>

<ul>
  <% @blogs.each do |blog| %>
    <li>
      <%= link_to blog.name, root_url(subdomain: blog.subdomain) %>
    </li>
    <% end %>
</ul>

app/views/blogs/new.html.erb
<h1>Want Your Own Subdomain!?</h1>
<%= form_for @blog do |f| %>
  <%=f.label :name %>
  <%=f.text_field :name %>
  <%=f.label :subdomain %>
  <%=f.text_field :subdomain %>
  <%= f.submit "Create Blog" %>
<% end %>

app/views/blogs/show.html.erb
<h1><%= @blog.name %></h1><br />
<h3><%= link_to "Make A New Blog Post", :controller => "posts", :action => "new"%></h3><br>
<% @blog.posts.each do |post| %>
<h3><%= post.title %></h3>
<p><%= truncate post.body, length: 160 %></p>
<%= link_to "Read More", post %>
<% end %>
<h3><%= link_to "Go To Blog Directory", root_url(:subdomain => "false") %></h3><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subdomain</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "http://yandex.st/bootstrap/3.0.2/css/bootstrap.min.css", media: "all" %>
  <%= javascript_include_tag "http://yandex.st/bootstrap/3.0.2/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class= "container">
  <%= yield %>
</div>
</body>
</html>

app/views/posts/create.html.erb
<%= @post.title %><br>
<%= @post.body %>
<br><h3><%= link_to "Go To Blog Directory", root_url(:subdomain => "false")%></h3><br>
<%= link_to "Go to Your Blog", :controller => "blogs", :action => "show" %>

app/views/posts/new.html.erb
<h1>Make A New Post!</h1>
  <%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br><br>
  <%= f.label :body %>
  <%= f.text_area :body %><br><br>
  <%= f.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<center>
	<h1>Title:</h1>
	<h4><%= @post.title %></h4><br>
</center>

<center>
	<h1>Body:</h1>
	<h4><p><%= @post.body %></p><br></h4>
</center>

<center>
	<%= link_to "Go Back To Your Blog", root_url %>
</center>